# _config.yml — Jekyll-Konfiguration für GitHub Pages

# Seitentitel und Beschreibung
title: Fractur App  Rechtliches
description: "Datenschutzerklärung, Nutzungsbedingungen und Impressum"

markdown: kramdown
theme: jekyll-theme-minimal


# Liste der HTML-Dateien, die in der Website enthalten sein sollen
include:
  - privacy_policy.html
  - tos.html
  - impressum.html
